# wurstmeister
version: '3'
services:
    zookeeper1:
        image: bitnami/zookeeper:3
        hostname: zookeeper1
        ports:
            - "2181:2181"
        environment:
            - ZOO_MY_ID=1
            - ZOO_PORT=2181
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
        volumes:
            - ./zookeeper1/data:/data
            - ./zookeeper1/datalog:/datalog
    kafka1:
        image: bitnami/kafka:2
        hostname: kafka1
        ports:
            - "9092:9092"
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka1
            - KAFKA_ADVERTISED_PORT=9092
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181
            - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        volumes:
            - ./kafka1/data:/var/lib/kafka/data
            - /var/run/docker.sock:/var/run/docker.sock            
        depends_on:
            - zookeeper1
    postgresql1:
        image: postgres
        hostname: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=supersecret
networks:
    default:
        external:
            name: kafkanet