# wurstmeister
version: '3'
services:
    zookeeper1:
        image: strimzi/kafka:latest-kafka-2.4.0
        hostname: zookeeper1
        command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2181:2181"
        environment:
            - ZOO_MY_ID=1
            - ZOO_PORT=2181
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
            - LOG_DIR=/tmp/logs
        volumes:
            - ./zookeeper1/data:/data
            - ./zookeeper1/datalog:/datalog
    kafka1:
        image: strimzi/kafka:latest-kafka-2.4.0
        hostname: kafka1
        command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
            LOG_DIR: /tmp/logs
        volumes:
            - ./kafka1/data:/var/lib/kafka/data
            - /var/run/docker.sock:/var/run/docker.sock            
        depends_on:
            - zookeeper1
networks:
    default:
        external:
            name: kafkanet